### ISSUE TITLE
WASHb Kenya page unresponsive

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/EdaLoadingIssues#13]
When I click to look at data for Cluster ID for WASHb Kenya (using qa.restricted on Chrome), the page freezes. The loading icon stops moving and I cannot click on anything else on the page. Soon after the page crashes entirely

![image](https://user-images.githubusercontent.com/25450900/136613090-e4638852-8f3a-4b30-9f1a-d1dc67b6a7e8.png)

**Comment by steve-fischer-200** [comment]
This is a data loading issue.  The phase 1 solution is, in the database, and in the owl file, to set the **DisplayType** of this variable to **Hidden**

in Phase 2 we probably want to introduce a **DisplayType** of **downloadOnly** (or similar)

@SheenaTomko also, we want to survey live site **hidden** variables, and make them similarly hidden in EDA

**Comment by SheenaTomko** [comment]
@steve-fischer-200 we surveyed hidden variables on the live site and collated them[ here](https://docs.google.com/spreadsheets/d/1p9Xy0xVBQz16DV1xV7mGukWNeY-_tFEzhii4MD0vupk/edit#gid=0). 

I'm closing this ticket since it should be fixed when Jay reloads the study, and will open a new phase 2 ticket for annotating and handling different types of hidden variables
