### ISSUE TITLE
Bug: Year variables should not pass through the origin

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/EdaLoadingIssues#21]
It doesn't make sense to have year variables pass through the origin on visualizations. We may need a new annotation prop for these? For example, see "Birth Year" in SCORE S mansoni RCT:

**Histogram in subset tab**
![image](https://user-images.githubusercontent.com/25450900/144465407-842c9d97-ee43-4c2d-9f88-0dd275ef0d34.png)

**Box plot in vis tab**
![image](https://user-images.githubusercontent.com/25450900/144465112-33c0a2f1-8b23-4151-8532-c4c7520ba41e.png)

**Comment by moontrip** [comment]
I have noticed this long time ago when implementing boxplot Viz. If I remember correctly, the issue was that those year variables  like birth year, enrollment year, etc. was set to type: number, not date: if they are set to date, then I think those plots would be correctly shown with little change at frontend codes.

**Comment by SheenaTomko** [comment]
Looked at all year variables in the owl file and checked loaded studies. Most year variables only had a few values (<6) and showed as categorical, so we may want to recheck after we switch to displaying all continuous variables as histograms. 

For now, only the original variable/study needs fixing. @nkittur-uga, please have Jay patch/reload SCORE S mansoni RCT so that "Birth year" has the type "date" rather than "number"

**Comment by danicahelb** [comment]
paused until switch to display all continuous vars as histograms, regardless of # of unique values

**Comment by SheenaTomko** [comment]
The switch to make all continuous vars histograms has been done. Some studies have already either updated year to forceStringType or set a min/max range for the variable. From Jay via slack, if we want to load year as a "date" type as DK suggested, 

> The database automatically adds a default month and day, the first day of the current month.
> If we go to the trouble of loading a year as a date type, we would have to have some way of applying the same format when retrieving it, otherwise we insert '2001' and retrieve '2001-02-01' (if it was inserted today)

This is obviously not ideal. My recommendation is to update the owl files for the following studies now to include a defaultDisplayRangeMin, defaultDisplayRangeMax, and defaultBinWidth that makes sense for the values for the following studies (which is what Nupur did for SCORE S. mansoni RCT, which is where this was first identified):

@danicahelb 
WASH-B Bangladesh: Year, Household year
WASH-B Kenya: Enrollment year, Household year, Anthropometry year, Symptoms year

@nkittur-uga 
GEMS1: Enrollment year
GEMS1 HUAS: Birth year
GAMIN: Year 
G-ANC: Previous delivery year, Child birth year, Baseline survey year, Antenatal survey year, GANC meeting year

@SheenaTomko 
Amazonia Brazil ICEMR: Hospitalization year, Hospitalization year 2, Hospitalization year 3 
PROMOTE: Child 1-7 delivery year
Southeast Asia ICEMR: Birth year

**Comment by SheenaTomko** [comment]
I am closing this and marking it as complete. Nupur, Danica, and I updated the conversion/owl files for the studies listed above to add a default min, max, and bin width. These changes will be implemented as the studies are reloaded.
