### ISSUE TITLE
EDA Downloads: Add full dataset files

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/EdaLoadingIssues#37]
For the downloads tab of the EDA, mbio is hoping to make available those same files that are currently on the live site.

For example, .biom files and sample details.

**Comment by wbazant** [comment]
Jay made a download file dumper for ClinEpi in ApiCommonData::Load::Plugin::MakeEntityDownloadFiles. If we're trying to make similar files to the ones on the live site it's not directly usable for MBio - I would instead adapt the current way to make files.

The existing code is here:
 MicrobiomeWorkflow::Main::WorkflowSteps::MakeDownloadFiles
 
 and it uses common code for reading result files + a specific bit to write them out, the class is
 ApiCommonData::Load::MBioResultsTable::AsText.
 
One part of MicrobiomeWorkflow::Main::WorkflowSteps::MakeDownloadFiles that would need to change is where it should get sample details (look for calls to the `addSampleDetails` method) - getting that from the data in the database that's "on EDA", or better from files on disk so it also works without the database, will be good programming!
 
The most interesting modification needed for MicrobiomeWorkflow::Main::WorkflowSteps::MakeDownloadFiles is to make it produce files for multiple entities for a study.
 
 I estimate this task will take about two weeks, but it would be really fun two weeks - so it's a great task, of potential interest to anyone who might enjoy Perl and object-oriented programming!

**Comment by asizemore** [comment]
Thanks @wbazant !

**Comment by asizemore** [comment]
Closing - @jaycolin added the full dataset download files last week.

**Comment by asizemore** [comment]
@SheenaTomko Dan is about to go on vacation - would someone from clinepi mind helping us with the qa?

**Comment by asizemore** [comment]
This issue should has become only about the full (non-subsetting) eda files. So the only files to qa are the ones that are under Full Dataset. We won't be adding any of the biom files or other auxiliary files at least until b60, and these will get their own ticket.

**Comment by SheenaTomko** [comment]
Qc'd by looking at a couple of studies

BONUS - data is reshaped in the new download files. Looks like the live site in the sample characteristics file has one row per sample per variable. On feature, I get one file with all participant level variables, one with sample level variables, and another with relative abundance data that is huge. It looks like all variables are there as I'd expect. However, it looks like multiple samples could have been collected per participant. On the feature participant file download, I only have one row of data per participant, so the same age, fecal fat %, etc. is associated with all samples from that participant rather than having one row per repeated measure. I think the data need to be reloaded with a Participant Repeated Measures entity added. All longitudinal participant variables should be loaded on that record.

Bangladesh 5 year - same problem as above with participant repeated measures. We're essentially losing all data on the participant except data collected alongside the first sample. I also tried looking at the assay download file from the feature site and comparing it to the taxa relative abundance file from the live site, but it's a little hard to directly compare since it seems like the computations are different

@asizemore I don't think the issue with participant repeated measures is fixable before the release, so my advice is to add a banner statement indicating people should download data from the live site, not feature

**Comment by asizemore** [comment]
@SheenaTomko thank you for the thorough investigation!! The banner is a great idea. I'll make a ticket!

**Comment by SheenaTomko** [comment]
Moving this ticket to complete since Ann made another ticket to address the repeated measure issue
