### ISSUE TITLE
Backend: categorical integers being displayed as numbers with a decimal point (ie, '1.0' instead of '1')

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/EdaLoadingIssues#5]
Backend: Subsetting service sometimes returns different values in the tabular endpoint from what it claims in the variables vocabulary 

this may be specific to categorical numbers. idk. the case i have evidence for is Score S. mansoni participant term 'Study timepoint'

if i hit `studies/SCORECX01-1` i can see this term claims to have a vocabulary of '1', '2', '3', '4', '5'
if i hit `studies/SCORECX01-1/entities/EUPATH_0000096/tabular` asking for this term i get values like '1.0', '2.0', '3.0', '4.0', '5.0'

this will break boxplot for this term, at a min.

**Comment by danicahelb** [comment]
Steve upgraded the subsetting service to handle a new Integer datatype.  issue has been moved to the EdaLoadingIssues repo, which is issues for jay/john to deal with

**Comment by jaycolin** [comment]
Fixed in ApiCommonData/Load/plugin/perl/LoadAttributesFromEntityGraph.pm commit c6710b9b5be27f993b9456fbcf393518bad0818c

**Comment by SAK22** [comment]
Still has decimal points.

**Comment by SheenaTomko** [comment]
@SAK22, I'm going to mark this as complete because it's something that is now fixed when Jay reloads a study, and has been fixed for studies like PRISM2, India ICEMR Meghalaya, and others. However a separate bug was identified after this fix was made. I reported it here: https://github.com/VEuPathDB/EdaNewIssues/issues/146
