### ISSUE TITLE
Map: Split variable for pathogen presence in two

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/EdaLoadingIssues#67]
In order to prevent individuals and pools being compared in visualizations, or to mislead people into thinking these data are truly homogeneous, we should split the pathogen presence variable into two variables instead. this was discussed in map ux on May 4th 2023. see notes [here](https://veupathdb.atlassian.net/l/cp/DdrX21Lf).

It may be other terms will require similar treatment, i dont think we know yet. but we can make tickets for those separately if that turns out to be the case.

**Comment by bobular** [comment]
w.r.t. my analysis here https://github.com/VEuPathDB/EdaLoadingIssues/issues/68#issuecomment-1618928876

Since we are going wide with pathogen results: both presence/absence and prevalence, and that presence/absence will never play in Plan D*, there is actually no need to do this ticket.


\* furthermore, there's no need for presence/absence on individual specimens to play in plan D, which contradicts the decision made in the confluence notes linked above.  Reasoning is that n is always 1!
